#!/bin/bash

# Update Git submodules
git submodule update --init

# Install Python packages using pip
pip install  lxml pelican markdown gevent

# Optionally, you can add more commands or customizations here.
